name: Deploy to dev.schoolbooster.at

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to dev.schoolbooster.at
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: "${{ secrets.GIT_SSH_USER }}@${{ secrets.GIT_SSH_HOST }}"
          privateKey: ${{ secrets.GIT_SSH_PRIVATE }}
          command: |
            cd /www/dev/schoolbooster
            git stash
            git pull
